/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elgamal_l;

import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author buida
 */
public class GUI_ELGAMAL extends java.awt.Frame {
    
    int max = 2147483647, min = 1000;
    long k;
    /**
     * Creates new form GUI_ELGAMAL
     */
    public GUI_ELGAMAL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_receive = new javax.swing.JButton();
        txt_p2 = new javax.swing.JTextField();
        txt_beta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_p1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_decrypt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_banro2 = new javax.swing.JTextArea();
        btn_clear = new javax.swing.JButton();
        btn_generation = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_banro1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_banma2 = new javax.swing.JTextArea();
        btn_encrypt = new javax.swing.JButton();
        txt_alpha = new javax.swing.JTextField();
        txt_a = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_banma1 = new javax.swing.JTextArea();

        setBackground(java.awt.Color.lightGray);
        setPreferredSize(new java.awt.Dimension(930, 470));
        setResizable(false);
        setTitle("Gui_ELGAMAL");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_receive.setText("Receive Ciphertext");
        btn_receive.setName("btn_receive"); // NOI18N
        btn_receive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_receiveActionPerformed(evt);
            }
        });
        add(btn_receive, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, 20));

        txt_p2.setEditable(false);
        txt_p2.setName("txt_p2"); // NOI18N
        add(txt_p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 80, 20));

        txt_beta.setEditable(false);
        txt_beta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_beta.setName("txt_beta"); // NOI18N
        add(txt_beta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 80, 20));

        jLabel2.setText("Alpha");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, 20));

        txt_p1.setEditable(false);
        txt_p1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_p1.setName("txt_p1"); // NOI18N
        add(txt_p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 80, 20));

        jLabel3.setText("P");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, 20));

        jLabel4.setText("Beta");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, 20));

        btn_decrypt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_decrypt.setText("Decrypt");
        btn_decrypt.setName("btn_decrypt"); // NOI18N
        btn_decrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_decryptActionPerformed(evt);
            }
        });
        add(btn_decrypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 100, 40));

        txt_banro2.setEditable(false);
        txt_banro2.setColumns(20);
        txt_banro2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_banro2.setLineWrap(true);
        txt_banro2.setRows(5);
        txt_banro2.setName("txt_banro2"); // NOI18N
        jScrollPane1.setViewportView(txt_banro2);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 310, 100));

        btn_clear.setText("Clear");
        btn_clear.setName("btn_clear"); // NOI18N
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        btn_generation.setText("Generation Key");
        btn_generation.setName("btn_generation"); // NOI18N
        btn_generation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generationActionPerformed(evt);
            }
        });
        add(btn_generation, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 20));

        txt_banro1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_banro1.setLineWrap(true);
        txt_banro1.setRows(5);
        txt_banro1.setName("txt_banro1"); // NOI18N
        jScrollPane3.setViewportView(txt_banro1);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 310, 100));

        txt_banma2.setEditable(false);
        txt_banma2.setColumns(20);
        txt_banma2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_banma2.setLineWrap(true);
        txt_banma2.setRows(5);
        txt_banma2.setName("txt_banma2"); // NOI18N
        jScrollPane4.setViewportView(txt_banma2);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 310, 100));

        btn_encrypt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_encrypt.setText("Encrypt");
        btn_encrypt.setName("btn_encrypt"); // NOI18N
        btn_encrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encryptActionPerformed(evt);
            }
        });
        add(btn_encrypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 100, 40));

        txt_alpha.setEditable(false);
        txt_alpha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_alpha.setName("txt_alpha"); // NOI18N
        add(txt_alpha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 80, 20));

        txt_a.setEditable(false);
        txt_a.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_a.setName("txt_a"); // NOI18N
        add(txt_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 80, 20));

        jLabel5.setText("P");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, 20));

        jLabel6.setText("a");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, 20));

        txt_banma1.setEditable(false);
        txt_banma1.setColumns(20);
        txt_banma1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_banma1.setLineWrap(true);
        txt_banma1.setRows(5);
        txt_banma1.setName("txt_banma1"); // NOI18N
        jScrollPane5.setViewportView(txt_banma1);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 310, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void btn_generationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generationActionPerformed
        // TODO add your handling code here:
        int p;
        long a, alpha, beta;
        Random genaration = new Random();
        do {
            p = genaration.nextInt((max - min)) + min;
        } while (CheckSNT(p) == false);
        
        txt_p1.setText("" + p);
        txt_p2.setText("" + p);
        //set a [2, p-2]
        a = genaration.nextInt(p - 4) + 2;
        txt_a.setText("" + a);
        //set alpha [1, p-1]
        alpha = genaration.nextInt((int) ((p - 1))) + 1;
        txt_alpha.setText("" + alpha);
        //set beta = alpha^a mod p
        beta = BinhPhuongNhan(alpha, a, p);
        txt_beta.setText("" + beta);
        //k la so bi mat [0, p-2]
        k = genaration.nextInt((int) (p - 1));
    }//GEN-LAST:event_btn_generationActionPerformed
    
    private void btn_encryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encryptActionPerformed
        try {
            if (txt_p1.getText().length() == 0
                    || txt_alpha.getText().length() == 0
                    || txt_beta.getText().length() == 0
                    || txt_a.getText().length() == 0) {
                showDialog("Bạn chưa Genenation key!");
                return;
            }
            if (txt_banro1.getText().length() == 0) {
                showDialog("Hãy nhập thông tin cần mã hóa trước !");
                return;
            }
            txt_banma1.setText("");
            txt_banma2.setText("");
            txt_banro2.setText("");
            // ma hoa ra dang chu
            encrypt_String();
            //ma hoa ra dang so
//            encrypt_ArrayLong();

            // e y1= alpha ^k  mod p
            // e y2 = x* beta^k mod p
        } catch (Exception e) {
            showDialog("Bạn chưa Genenation key!");
        }
    }//GEN-LAST:event_btn_encryptActionPerformed
 
    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txt_a.setText("");
        txt_alpha.setText("");
        txt_beta.setText("");
        txt_p1.setText("");
        txt_p2.setText("");
        txt_banro1.setText("");
        txt_banro2.setText("");
        txt_banma1.setText("");
        txt_banma2.setText("");

    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_receiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_receiveActionPerformed
        // TODO add your handling code here:
        if (txt_banma1.getText().length() == 0) {
            showDialog("Không có bản mã nào!");
            return;
        }
        txt_banma2.setText(txt_banma1.getText());
    }//GEN-LAST:event_btn_receiveActionPerformed

    private void btn_decryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_decryptActionPerformed
        // TODO add your handling code here:
        try {
            if (txt_banma2.getText().length() == 0) {
                showDialog("Không có thông tin nào cần giải mã!");
                return;
            }
            //giai ma voi ban ma la string
            decrypt_String();
            // giai ma voi ban ma la so
//            decrypt_ArrayLong();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Giải mã thất bại",
                    "Thông báo",
                    JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btn_decryptActionPerformed
 
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_ELGAMAL().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_decrypt;
    private javax.swing.JButton btn_encrypt;
    private javax.swing.JButton btn_generation;
    private javax.swing.JButton btn_receive;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField txt_a;
    private javax.swing.JTextField txt_alpha;
    private javax.swing.JTextArea txt_banma1;
    private javax.swing.JTextArea txt_banma2;
    private javax.swing.JTextArea txt_banro1;
    private javax.swing.JTextArea txt_banro2;
    private javax.swing.JTextField txt_beta;
    private javax.swing.JTextField txt_p1;
    private javax.swing.JTextField txt_p2;
    // End of variables declaration//GEN-END:variables

    //hien thi dialog thong bao
    public void showDialog(String s) {
        JOptionPane.showMessageDialog(this,
                s,
                "Thông báo",
                JOptionPane.OK_OPTION);
    }
    // ham kiem tra so nguyen to
  public boolean CheckSNT(long n) {
        // so nguyen n < 2 khong phai la so nguyen to
        if (n < 2) {
            return false;
        }
        // check so nguyen to khi n >= 2
        for (int i = 2; i <= Math.sqrt(n); i++) {
            if (n % i == 0) {
                return false;
            }
        }
        return true;
    }
  // binh phuong va nhan trong modulo
   public long BinhPhuongNhan(long alpha, long a, long p) {
        long ketqua = 1, n = p, x = alpha;
        String k = Integer.toBinaryString((int) a);//chuyen sang nhi phan
        int i = 0;
        while (i < k.length()) {
            ketqua *= ketqua;
            ketqua %= n;
            if (k.charAt(i) == '1') {
                ketqua *= x;
            }
            ketqua %= n;
            i++;
        }
        return ketqua;
    }
   // ham ma hoa tra ve dang chu
      public void encrypt_String() {
        long p = Integer.valueOf(txt_p1.getText());
        long alpha = Integer.valueOf(txt_alpha.getText());
        long beta = Integer.valueOf(txt_beta.getText());
        //tính y1
        long y1 = BinhPhuongNhan(alpha, k, p);
        long y2;
        // lay ban ro 
        String ban_ro = txt_banro1.getText();
        String ban_ma = "";
        //du y1 vao chuoi ban ma
        ban_ma += y1;
        int i = 0;
        while (i < ban_ro.length()) {
            //phan tach cac gia tri trong ban ma bang dau "-" sau moi vong lap
            ban_ma += "-";
            //tính y2 roi dua vào chuoi banma
            ban_ma += ((ban_ro.charAt(i) * BinhPhuongNhan(beta, k, p)) % p);
            i++;
        }
        // chuyen ban ma string -> byte
        byte[] banmaByte = ban_ma.getBytes(StandardCharsets.UTF_8);
        // chuyen ban ma byte -> string dạng base64
        ban_ma = Base64.getEncoder().encodeToString(banmaByte);
        // dua chuoi ban ma dang base64 vào o text 
        txt_banma1.setText(ban_ma);
    }
      // ham ma hoa tra ve dang so
    public void encrypt_ArrayLong() {
        txt_banma1.setText("");
        txt_banma2.setText("");
        txt_banro2.setText("");
        // TODO add your handling code here:
        Random genaration = new Random();
        int p = Integer.valueOf(txt_p1.getText());
        long alpha = Integer.valueOf(txt_alpha.getText());
        long beta = Integer.valueOf(txt_beta.getText());
        //tính y1
        long y1 = BinhPhuongNhan(alpha, k, p);
        long y2;
        // lay ban ro 
        String ban_ro = txt_banro1.getText();
        String ban_ma = "";
        //du y1 vao chuoi ban ma
        ban_ma += y1;
        int i = 0;
        while (i < ban_ro.length()) {
            //phan tach cac gia tri trong ban ma bang dau "-" sau moi vong lap
            ban_ma += "-";
            //tính y2 roi dua vào chuoi banma
            ban_ma += ((ban_ro.charAt(i) * BinhPhuongNhan(beta, k, p)) % p);
            i++;
        }
        txt_banma1.setText(ban_ma);
    }
   
   // ham giai ma voi ban ma o dang chu
      public void decrypt_String() {
        int p = Integer.valueOf(txt_p1.getText());
        long a = Integer.valueOf(txt_a.getText());
        // lay ban ma hoa tu o text mahoa 2 dạng byte
        byte[] banmaByte = Base64.getDecoder().decode(txt_banma2.getText());
        // chuyen ban ma byte -> string
        String ban_ma = new String(banmaByte);
        // tach ban ma thanh 1 mảng các chuoi bang ky tu "-"
        String[] banmaString = ban_ma.split("-");
        long[] banmaLong = new long[banmaString.length];
        // chuyen ban ma dang mang string -> mang long
        for (int i = 0; i < banmaString.length; i++) {
            banmaLong[i] = Long.valueOf(banmaString[i]);
        }
        String ban_ro = "";
        // tính mu cua y1 khi giai ma
        // vì (y1^a)^-1 mod p = y1^(p-a-1) mod p
        long m = p - a - 1;
        // tinh y1^(p-a-1) mod p
        long y1_de = BinhPhuongNhan(banmaLong[0], m, p);

        // giai ma x = (y2*y1_de ) mod p
        for (int i = 1; i < banmaLong.length; i++) {
            // chen tung phan tu giai ma duoc vao chuoi banro
            ban_ro += (char) ((banmaLong[i] * y1_de) % p);
        }
        // set ban ro vao text ban ro 2
        txt_banro2.setText(ban_ro);
    }
      // ham giai ma voi ban ma o dang so
    public void decrypt_ArrayLong() {
        int p = Integer.valueOf(txt_p1.getText());
        long a = Integer.valueOf(txt_a.getText());
        //lay ban ma tu o text ban ma 2
        String ban_ma = txt_banma2.getText();
        // tach ban ma thanh 1 mảng các chuoi bang ky tu "-"
        String[] banmaString = ban_ma.split("-");
        long[] banmaLong = new long[banmaString.length];
        // chuyen ban ma dang mang string -> mang long
        for (int i = 0; i < banmaString.length; i++) {
            banmaLong[i] = Long.valueOf(banmaString[i]);
        }
        String ban_ro = "";
        // tính mu cua y1 khi giai ma
        // vì (y1^a)^-1 mod p = y1^(p-a-1) mod p
        long m = p - a - 1;
        // tinh y1^(p-a-1) mod p
        long y1_de = BinhPhuongNhan(banmaLong[0], m, p);

        // giai ma x = (y2*y1_de ) mod p
        for (int i = 1; i < banmaLong.length; i++) {
            // chen tung phan tu giai ma duoc vao chuoi banro
            ban_ro += (char) ((banmaLong[i] * y1_de) % p);
        }
        // set ban ro vao text ban ro 2
        txt_banro2.setText(ban_ro);
    }

}
